name: pipeline

channels:
  - pytorch
  - simpleitk
  - conda-forge
  - defaults

dependencies:
  - python=3
  - cython
  - jupyterlab
  - nodejs

  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - plotly
  - pymysql
  - pytorch
  - requests
  - scipy
  - seaborn
  - simpleitk
  - sqlalchemy
